name: Android Zip Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Unzip project
      run: |
        unzip LauncherSwap_AdvancedSource.zip
        unzip -l LauncherSwap_AdvancedSource.zip

    - name: Find gradlew and set permissions
      run: |
        GRADLEW=$(find . -type f -name gradlew)
        echo "Found gradlew at: $GRADLEW"
        chmod +x "$GRADLEW"

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build APK
      run: |
        PROJECT_DIR=$(find . -type f -name gradlew | xargs dirname)
        cd "$PROJECT_DIR"
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LauncherSwap-APK
        path: "**/build/outputs/apk/debug/*.apk"
