name: Android Zip Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install unzip tool
      run: sudo apt-get install unzip

    - name: Unzip project into folder
      run: unzip LauncherSwap_AdvancedSource.zip -d LauncherSwap

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant permission to Gradle wrapper
      run: chmod +x LauncherSwap/gradlew

    - name: Build APK
      run: cd LauncherSwap && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LauncherSwap-APK
        path: LauncherSwap/app/build/outputs/apk/debug/*.apk
